#ifndef WAVE_H
#define WAVE_H

#include <fstream>

#define WAVE_PCM_FORMAT			1
#define WAVE_FIRST_BLOC_SIZE	12
#define WAVE_SECOND_BLOC_SIZE	26
#define WAVE_THIRD_BLOC_SIZE	8
#define WAVE_HEADER_SIZE		(WAVE_FIRST_BLOC_SIZE + WAVE_SECOND_BLOC_SIZE + WAVE_THIRD_BLOC_SIZE)

#define KINECT_FREQUENCY		16000
#define KINECT_CHANNELS			1
#define KINECT_BITS_PER_SAMPLE	16
#define KINECT_BYTES_PER_BLOC	(KINECT_CHANNELS * (KINECT_BITS_PER_SAMPLE/8))
#define KINECT_BYTES_PER_SEC	(KINECT_BYTES_PER_BLOC * KINECT_FREQUENCY)

void writeWaveHeader(std::ofstream& f, int audioDataSize);

#endif
